fix: добавить единое имя для инпутов радио, реализовать переключение …
yaremchuken/flophouse-project pull request #66
Opened 2021-12-16 10:20 UTC by ElenaSolov

…классов средствами CSS

2021-12-16 10:52 UTC, yaremchuken approved these changes

2021-12-23 10:10 UTC, const-se-praktikum requested changes

2021-12-23 10:10 UTC, const-se-praktikum commented on .vscode/settings.json
> +{
Папку `.vscode` следует удалить из репозитория, и добавить ее в `.gitignore`

2021-12-23 10:10 UTC, const-se-praktikum commented on scripts/script.js
> +//Переключение классов реализовано средствами CSS
Закомментированный код лучше удалять совсем. Все равно история изменений есть в гите, если вдруг потребуется откатиться

2021-12-23 10:23 UTC, const-se-praktikum commented on blocks/form/__radio/form__radio.css
> +.form__radio:checked + .form__radio-icon {
👍

2021-12-24 07:36 UTC, merged